vimc/montagu-webmodels

src/main/kotlin/org/vaccineimpact/api/models/GAVISupportLevel.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-555

Add legacy support levels.

---

src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimateSet.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-999

i999: Burden estimate status

---

src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimate.kt
src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimateSet.kt

Part of https://vimc.myjetbrains.com/youtrack/issue/VIMC-949

Models for uploading different kinds of burden estimates

---

src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimateSet.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-930

Add helper methods.

---

src/main/kotlin/org/vaccineimpact/api/models/ModelRunParameterSet.kt

added field disease to model parameters run sets schema

i1253 - added field disease to model parameters run sets schema

---

src/main/kotlin/org/vaccineimpact/api/models/helpers/OneTimeAction.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1045

i1045: Remove burdens one time action.

---

src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimateSet.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1321

i1321: Add "partial" set status, to reflect database

---

src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimateSet.kt
src/main/kotlin/org/vaccineimpact/api/models/validation/ValidationAnnotations.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1398

Add rule for "required when"

---

src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimateSet.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1325

i1325: Add isStochastic to BurdenEstimateSet

---

src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimateSet.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1325

i1325: Make isStochastic a function so it doesn't get serialized

---

src/main/kotlin/org/vaccineimpact/api/models/helpers/ContentTypes.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1423

i1423: Add list of acceptable CSV types

---

src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimate.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1480

Switch outcomes to floats

---

src/main/kotlin/org/vaccineimpact/api/models/BurdenEstimate.kt
src/main/kotlin/org/vaccineimpact/api/models/Expectations.kt

It's now even less clear that this class should live in the models project, but not really sure where it would be better off?

I1951 - generate sequence of rows from expectations

---

src/main/kotlin/org/vaccineimpact/api/models/Expectations.kt
src/main/kotlin/org/vaccineimpact/api/models/YearRange.kt
src/main/kotlin/org/vaccineimpact/api/models/responsibilities/ResponsibilityAndTouchstone.kt
src/main/kotlin/org/vaccineimpact/api/models/responsibilities/ResponsibilityDetails.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1965

i1965: New models for returning responsibility details

---

src/main/kotlin/org/vaccineimpact/api/models/responsibilities/Responsibility.kt
src/main/kotlin/org/vaccineimpact/api/models/responsibilities/ResponsibilityAndTouchstone.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-1965

i1965: Allow repositories to return responsibility ID

---

src/main/kotlin/org/vaccineimpact/api/models/ExpectationMapping.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2010

Include disease in ExpectationMapping

---

src/main/kotlin/org/vaccineimpact/api/models/helpers/OneTimeAction.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2056

i2056: Remove unused onetime action

---

src/main/kotlin/org/vaccineimpact/api/models/AuthenticationResponse.kt

https://vimc.myjetbrains.com/youtrack/issue/VIMC-2073

i2073: Allow comparison of SuccessfulAuthentication objects

---

src/main/kotlin/org/vaccineimpact/api/models/Disease.kt
src/main/kotlin/org/vaccineimpact/api/models/ResearchModel.kt

Preliminary PRs to add disease to model class - please reassign ticket to me after review.
The other PR: https://github.com/vimc/montagu-api/pull/394

Added disease to ResearchModelDetails

---

src/main/kotlin/org/vaccineimpact/api/models/AppliedExpectation.kt
src/main/kotlin/org/vaccineimpact/api/models/CountryOutcomeExpectations.kt
src/main/kotlin/org/vaccineimpact/api/models/ExpectationMapping.kt
src/main/kotlin/org/vaccineimpact/api/models/Expectations.kt
src/main/kotlin/org/vaccineimpact/api/models/OutcomeExpectations.kt
src/main/kotlin/org/vaccineimpact/api/models/TouchstoneModelExpectations.kt
src/main/kotlin/org/vaccineimpact/api/models/responsibilities/ResponsibilityDetails.kt

Another pair of preliminary PRs, to add scenarios to the /expectations endpoint.
Here's the other one: https://github.com/vimc/montagu-api/pull/397

Added scenarios to TouchstoneModelExpectations

---

src/main/kotlin/org/vaccineimpact/api/models/CoverageRow.kt

The model changes for https://github.com/vimc/montagu-api/pull/409

vimc-3149 CoverageRows may have gender

---

src/main/kotlin/org/vaccineimpact/api/models/Scope.kt
src/main/kotlin/org/vaccineimpact/api/models/expectations/CountryOutcomeExpectations.kt

Replace decprecated method and remove unused not null assertion.

updates as per kotlin 1.3

---

src/main/kotlin/org/vaccineimpact/api/models/CoverageIngestionRow.kt
src/main/kotlin/org/vaccineimpact/api/models/Gender.kt

See https://github.com/vimc/montagu-api/pull/437 for context

add CoverageIngestionRow

---

src/main/kotlin/org/vaccineimpact/api/models/CoverageUploadMetadata.kt

Goes along with https://github.com/vimc/montagu-api/pull/446

add coverage upload meta data class

---

src/main/kotlin/org/vaccineimpact/api/models/CoverageUploadMetadata.kt

Add property to shared model class

vimc-4465 Add activityType to CoverageUploadMetadata

---

src/main/kotlin/org/vaccineimpact/api/models/responsibilities/ResponsibilityRow.kt

Required for vimc/montagu-api#461

VIMC-4737 Export responsibilities summary for a touchstone

---

src/main/kotlin/org/vaccineimpact/api/models/expectations/CountryOutcomeExpectations.kt

not needed in latest version of kotlin

remove obsolete import
